### ISSUE TITLE
Several local files references as dependencies

### ISSUE THREAD

**Issue by SteveSmith16384** [Ivelate/Kubex#5]
Hi.  This is a great project BTW.  Just to let you know, in the .classpath file ( https://github.com/Ivelate/Kubex/blob/master/.classpath ), there are several local files references as dependencies (in C:/Users/Ivelate/Documents/Games Workspace/).  The only way for someone to get the source to compile is to hunt down these dependencies and add them manually.

**Comment by Ivelate** [comment]
Hello, thanks for the heads-up! Just fixed it. Thanks for taking the time to notify the error!
